# ========================
# DEV PROFILE
# ========================
# Activate with: --spring.profiles.active=dev
# or set env: SPRING_PROFILES_ACTIVE=dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false

logging.level.root=DEBUG
logging.level.com.ethara=DEBUG
logging.level.org.hibernate.SQL=DEBUG
